// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            pgtype.UUID
	FullName      pgtype.Text
	Username      pgtype.Text
	Email         string
	Photo         pgtype.Text
	UserActive    bool
	VerifiedEmail bool
	Password      string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
