// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         pgtype.Int4
	FullName   string
	Username   string
	Email      string
	Photo      pgtype.Text
	UserActive bool
	Password   string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
